### ISSUE TITLE
Stripe doesn't bind to the checkout button if the level is free when coming in.

### ISSUE THREAD

**Issue by ideadude** [strangerstudios/pmpro-donations#23] opened 2019-05-01 19:56 UTC
Donation-only level with $0 initial payment. Visit the checkout page. Change the donation amount to get the billing fields to show. Enter info and click submit. The form won't communicate with Stripe. The PMPro backend will not get the CC info, including expiration date and will complain about that. Now that the field is loaded with a value, the checkout will work. Also works if a non-zero ?donation param is passed into the URL.

**Comment by ronalfy** [comment] 2020-04-20 13:41
@dparker1005 @ideadude just bumping this. A customer is having the same issues as mentioned in this ticket.

**Comment by MaximilianoRicoTabo** [comment] 2023-08-02 21:14
@ideadude @dparker1005 @andrewlimaza can't reproduce this one. Not sure if i'm doing anything wrong.  i do see that dropdown change doesn't show billing fields but i think that's not the described bug. Once i was able to show billing fields i could submit form and i see with no problem in stripe dashboard test mode

<img width="1300" alt="image" src="https://github.com/strangerstudios/pmpro-donations/assets/1678457/60ffaebe-df1c-43d0-bdfd-296d4c56e7f3">
<img width="837" alt="image" src="https://github.com/strangerstudios/pmpro-donations/assets/1678457/ca65f0d8-c799-4031-9b40-bd1a4e6c268a">
<img width="1483" alt="image" src="https://github.com/strangerstudios/pmpro-donations/assets/1678457/78f92638-c94d-4b23-bd90-a4b5cc7d375b">


Is there any config i'm missing or step i should add in order to reproduce ?

**Comment by dparker1005** [comment] 2023-08-15 17:27
I also could not replicate. Closing issue as it seems to be resolved.

**Closed by dparker1005** 2023-08-15 17:27 UTC
