### ISSUE TITLE
Donations don't carry through properly

### ISSUE THREAD

**Issue by mlavanish** [strangerstudios/pmpro-donations#2] opened 2015-07-28 19:46 UTC
Hi,

When a user enters an initial donation, the amount will carry over to PayPal Express. However, when returning to the confirmation page at the website, the donation box and text appears again and is not populated with the donation amount. If the donation amount is left blank, PayPal will not charge the donation amount. However, the amount is recorded and reflected on the PMPRO order and checkout emails.

Is there any way to skip the additional donation box on the confirmation page, or at least to change the text to read something like "Please confirm your donation amount?"

Thanks!

PMPRO ver. 1.8.4.5
Donation Plugin ver. .2
Wordpress ver. 4.2.3

**Comment by kimcoleman** [comment] 2018-11-08 14:59
Another member has reported a similar issue - see: 
https://www.paidmembershipspro.com/forums/topic/donations-add-on-is-not-taking-payment-out-on-paypal/

**Comment by greathmaster** [comment] 2018-11-08 20:41
I cannot re-create this in the latest version (0.5) of the Add On. According to the readme we fixed this issue in version 0.3.1.

The similar behavior mentioned by @kimcoleman appears to be a different issue. I have created a separate issue for it and how to reproduce it here:

https://github.com/strangerstudios/pmpro-donations/issues/18

**Comment by dparker1005** [comment] 2020-08-07 19:07
We are closing this issue as there have been major updates since this bug was reported. If this is still an issue that you are experiencing on your site, please create a new GitHub Issue in this repository or <a href="https://www.paidmembershipspro.com/new-topic/">open a ticket in the PMPro Support Forum</a>.

**Closed by dparker1005** 2020-08-07 19:07 UTC
Labels: Blocking Next Release, Status: Need to Recreate, Type: Bug
